server:
  port: 8083
spring:
  application:
    name: jwtsecurity
  datasource:
    url: jdbc:postgresql://localhost:5432/jwt_security
    username: postgres
    password: root1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
    show-sql: true
    properties:
      hibernate: dialect:org.hibernate.dialect.PostgreSQLDialect
      format-sql: true